### ISSUE TITLE
Game does not close after player "sleeps"

### ISSUE THREAD

**Issue by squirlemaster42** [Programming-2/Lil-Sheds-Get-Good-In#5]
Plz fix

**Comment by will-a** [comment]
what do you mean

**Comment by will-a** [comment]
@squirlemaster42 we don't want it to close anymore, we want it to switch scenes right?

**Comment by will-a** [comment]
@squirlemaster42 i dont think the timer is being properly passed, the terminal is saying the current time is 0 in every tick, yet the timer still displays the correct value?

**Comment by will-a** [comment]
fixed
